// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cv11.EFCore;

#nullable disable

namespace CV11.Migrations
{
    [DbContext(typeof(VyukaContext))]
    partial class VyukaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CV11.EFCore.Hodnoceni", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<string>("ZkratkaPredmet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<double>("Znamka")
                        .HasColumnType("float");

                    b.HasKey("IdStudent", "ZkratkaPredmet");

                    b.HasIndex("ZkratkaPredmet");

                    b.ToTable("Hodnoceni");
                });

            modelBuilder.Entity("CV11.EFCore.Predmet", b =>
                {
                    b.Property<string>("Zkratka")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Zkratka");

                    b.ToTable("Predmet");
                });

            modelBuilder.Entity("CV11.EFCore.StudentPredmet", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<string>("ZkratkaPredmet")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdStudent", "ZkratkaPredmet");

                    b.HasIndex("ZkratkaPredmet");

                    b.ToTable("StudentsPredmet");
                });

            modelBuilder.Entity("cv11.EFCore.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CV11.EFCore.Hodnoceni", b =>
                {
                    b.HasOne("cv11.EFCore.Student", "Student")
                        .WithMany("Hodnoceni")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV11.EFCore.Predmet", "Predmet")
                        .WithMany("Hodnoceni")
                        .HasForeignKey("ZkratkaPredmet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CV11.EFCore.StudentPredmet", b =>
                {
                    b.HasOne("cv11.EFCore.Student", "Student")
                        .WithMany("StudentPredmety")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CV11.EFCore.Predmet", "Predmet")
                        .WithMany("StudentPredmety")
                        .HasForeignKey("ZkratkaPredmet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Predmet");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CV11.EFCore.Predmet", b =>
                {
                    b.Navigation("Hodnoceni");

                    b.Navigation("StudentPredmety");
                });

            modelBuilder.Entity("cv11.EFCore.Student", b =>
                {
                    b.Navigation("Hodnoceni");

                    b.Navigation("StudentPredmety");
                });
#pragma warning restore 612, 618
        }
    }
}
